name: 'Install Node and dependencies'

description: 'Set up Node and dependencies'
runs:
  using: composite
  steps:
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      shell: bash
      run: npm install