name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node and dependencies
        uses: ./.github/actions/install
      - name: Start PostgreSQL Database
        run: |
          docker-compose up -d && sleep 5s
      - name: Start migration
        run: npm run test:migrate
      - name: Run integration tests
        run: npm run test:integration